import React from 'react'
import './Terms.css'
import Header from '../home/Header/Header'
import Footer from '../home/Footer/Footer'

export default function Terms() {
    return (
        <div>
            <Header />
            <div className='gorTermsMain'>
                <p style={{ textAlign: 'center', fontSize: '45px', fontFamily: 'Freight Big Pro,serif' }}>Terms of Use</p>

                <p>Welcome to gorjana.com! Please take a few minutes to carefully review these Terms of Use and the Privacy Policy, which are hereby incorporated into these Terms of Use.</p>

                <p>gorjana.com (the "Website") is owned and operated by Gorjana & Griffin, Inc. ("gorjana"). By accessing or using this Website, you are agreeing to follow these rules and be bound by these Terms of Use. If you do not agree with any of the provisions in these Terms of Use or in the Privacy Policy, please do not use the Website. gorjana reserves the right to change these Terms of Use from time to time without prior notice.</p>

                <strong>USE OF WEBSITE</strong>
                <p>Subject to your compliance with these Terms of Use, gorjana allows you to access and make personal and non-commercial use of the Website. You may not use the Website for any resale or commercial use, including without limitation, the use of any information, services or Content (as defined below) on the Website, such as product listings, descriptions, or pricing. You may not make any derivative uses of any information, service or Content on the Website, download or copy any information, service or Content on the Website for the benefit of a third party, or use data mining, robots, bots, or similar data gathering and extraction tools.</p>
                <br />
                <p>You agree that you will not use this Website, or any of its Content or services for any illegal or prohibited purpose. You are also prohibited from accessing data not intended for you or logging onto an account that you are not authorized to access; attempting to breach our security measures; interfering in any way with the use of or access to the Website; attempting to decipher, decompile, disassemble or reverse engineer any software used by or on our Website; or using any engine, software, tool or other mechanism, including without limitation, browsers, spiders or robots, to navigate or search our Website.</p>
                <br />
                <p>You agree not to forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to us on or through the Website or any service offered on or through the Website. You agree not to impersonate or pretend that you are any other person or falsely claim you represent another person.</p>
                <br />
                <p>All rights not expressly granted to you in these Terms of Use are reserved and retained by gorjana.</p>

                <strong>YOUR ACCOUNT</strong>
                <p>In order to make a purchase, it is recommended to create an account. See the Privacy Policy for information related to the creation of an account. Creating an account allows you to save shipping and billing information for speedy checkout, check order status, review order history, create product wish lists to view online, and manage subscriptions.</p>
                <p>For your convenience, you may also log in and complete payment using alternative supported platforms.</p>
                <p>You are solely responsible for maintaining the confidentiality of your account and password and maintaining your account privacy settings, and you agree to accept responsibility for all activities that occur under your account or password.</p>

                <strong>ELECTRONIC COMMUNICATION</strong>
                <p>By using the Website, or by sending us emails, you are consenting to receive communications from us electronically. We may communicate with you by e-mail, or by posting notices on the Website. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
                <br />
                <br />

                <strong>INTELLECTUAL PROPERTY OWNED BY gorjana &amp; griffin</strong>
                <p>All content made available through the Website, including but not limited to text, information, pricing, graphics, descriptions, copy, page headers, artwork, photographs, images, logos, button icons, audio clips, video clips, data compilations and other content located on the Website (each and collectively, “Content”), is the property of gorjana and is protected by California, U.S.A. and international laws. The Website, portions thereof, and all Content are protected by copyright laws and may not be copied, modified, reproduced, posted, downloaded, transmitted, displayed, broadcast or distributed in any way, in whole or in part, without the prior written consent of gorjana.</p>
                <p>In addition, unless otherwise noted as belonging to a third party, all trademarks, service marks, trade dress, logos and icons on the Website are the exclusive property of gorjana. All other intellectual property and company names used on this Website not owned by gorjana are the property of their respective owners.</p>
                <p>Nothing in these Terms of Use or any other language on this Website is intended to create a license or give you any right to use any of the intellectual property or content on this Website without the express written consent of gorjana. gorjana actively enforces its intellectual property rights to the fullest extent of the law.</p>

                <strong>THIRD PARTY AFFILIATES</strong>
                <p>We may use third party advertising companies to serve or personalize ads when you visit the Website or thereafter. These companies may use information (not including your name, address, email address or telephone number) about your visits to this and other sites in order to provide advertisements on this site and other sites about goods and services that may be of interest to you. If you would like more information about this practice and to know your choices about not having this information used by these companies, please use this link for more information: http://optout.networkadvertising.org/?c=1. We do not share this information without your consent.</p>
                <p>We will never sell personally identifying information that you provide on the payment page or when you create an account on our Website (such as credit card information, name, birth date, gender, address, or phone numbers).</p>
                <p>The Website may reference or provide links to third party websites such as Twitter, Facebook, Pinterest, Instagram, YouTube, LinkedIn and advertisements. gorjana takes no responsibility and assumes no liability for any content, warranties, representations, purchases, or any statements or activities made on or in connection any third party websites.</p>

                <strong>SMS COMMUNICATION</strong>
                <p>If you elect to receive marketing text messages from gorjana, either via our website or by sending a text message indicating your consent, you are providing your prior express written consent to receive recurring marketing or promotional SMS text messages from us (each, a “Text Message”) sent through an automatic telephone dialing system. These may include cart abandon messages. Message frequency varies. This service is optional and is not a condition for purchase. You can opt out of receiving any further Text Messages from us at any time by replying “STOP” to any Text Message you receive from us. For help, reply “HELP” to any Text Message you receive from us or email customercare@gorjana.com.</p>
                <p>In addition to any fee of which you are notified, your mobile provider’s message and data rates may apply to our confirmation Text Message and all subsequent Text Message correspondence according to your individual rate plan provided by your wireless carrier. Please consult your mobile service carrier’s pricing plan to determine the charges for browsing data and sending and receiving Text Messages. Under no circumstances will we or our affiliates be responsible for any SMS messaging or wireless charges incurred by you or by a person that has access to your wireless device or telephone number. If your carrier does not permit SMS messages, you may not receive the Text Messages. Neither we nor the wireless carriers (such as T-Mobile) will be liable for any delays in the receipt of, or failure to deliver, any Text Messages, as delivery is subject to effective transmission from your network operator. Text Message services are provided on an “AS IS” basis.</p>
                <p>Data obtained from you in connection with any Text Message services may include your cell phone number, your provider’s name and the date, time and content of your text messages. We may use this information in accordance with our Privacy Policy to contact you and to provide the services you request from us. For more information on how we use telephone numbers, please read our Privacy Policy. If you change or deactivate the phone number you provided, you have an affirmative obligation to update your account information and the phone number(s) attached to your account to prevent us from inadvertently communicating with anyone who acquires any phone number(s) previously attributed to you, and any new phone number(s) you attach to your account may receive our standard marketing Text Messages unless you also unsubscribe via the above procedures.</p>

                <strong>BREACH OF SECURITY</strong>
                <p>gorjana takes your security information very seriously and will maintain strong practices in protecting your information. However, you understand that there are ways in which third parties can hack into or steal information from any website. You agree that gorjana is not responsible for any consequences from data breaches, hacking, and the like by third parties accessing information from gorjana or the Website.</p>
                <br />
                <br />

                <strong>APPLICABLE LAWS AND JURISDICTION</strong>
                <p>By purchasing goods from this Website, you agree that the offer and sale of those goods takes place in, and will be governed by the laws of the State of California.</p>
                <p>User access to this Website is governed by all applicable federal, state and local laws. All information available on the Website is subject to U.S. export control laws and may also be subject to the laws of the country where you reside. We make no representation that the Website is appropriate or available for use outside the United States, and access to the Website from territories where its content is illegal is prohibited. If you choose to access the Website from outside the United States, you are responsible for compliance with applicable local laws.</p>

                <strong>PRODUCT AND PRICING INFORMATION; ERRORS AND OMISSIONS</strong>
                <p>Information on this Website may contain typographical errors or inaccuracies and may not be complete or current. We therefore reserve the right to correct any errors, inaccuracies or omissions and to change or update information at any time without prior notice (including after you have submitted your order). Please note that such errors, inaccuracies or omissions may relate to product descriptions, pricing and availability. We also reserve the right to limit quantities (including after you have submitted your order).
                    Prices and availability of products on the Website are subject to change without notice. The Website contains a large number of products and it is always possible that, despite our best efforts, some of the products listed on the Website may be incorrectly priced. We are under no obligation to provide the product to you at the incorrect (lower) price, even after we have sent you an Order Confirmation or a Shipping Confirmation, if the pricing error is obvious and unmistakable and could have reasonably been recognized by you as a pricing error. Please be aware that Sale and Off Price Items all sales are final and no pricing adjustments will be granted.</p>
                <p>We have made every effort to display the colors of our products accurately as they appear on the Website. However, because the colors you see will depend on a number of factors, including your monitor, we cannot guarantee that your monitor's display of any color will be accurate. We do not warrant that the product descriptions are accurate, complete, reliable, current or error-free. If a product offered by the Website is not as described, your sole remedy is to return it in unused condition for a refund, subject to the return policies described above.</p>

                <strong>MOBILE</strong>
                <p>The Website contains services and features that are available to certain mobile devices. Your carrier's normal rates and fees apply. Not all mobile services or features on our website will work with all carriers or devices. By using our mobile services, you agree that we may communicate with you by electronic means to your mobile device and that certain information about your use of these services may be shared with us. If you change or deactivate your mobile phone number, you must promptly update your account information to ensure that we don't send your messages to a different person.</p>

                <strong>DISCLAIMER OF WARRANTIES AND LIMITATIONS OF LIABILITY</strong>
                <p>This Website and any information, products, content, materials, and any services included on or made available to you through the Website are provided on an "as is" and "as available" basis.<br /><br />

                    GORJANA & GRIFFIN MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, WITH REGARD TO THE WEBSITE, ITS CONTENT, ITS PRODUCTS OR ITS SERVICES. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, GORJANA & GRIFFIN DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.<br />

                    YOU EXPRESSLY AGREE THAT YOUR USE OF THE WEBSITE AND SERVICES OFFERED THROUGH THE WEBSITE IS AT YOUR SOLE RISK.</p><br />

                <p>IN NO EVENT WILL GORJANA & GRIFFIN BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM YOUR USE OF THIS WEBSITE, FROM YOUR USE OF ANY GORJANA & GRIFFIN SERVICE, OR FROM ANY INFORMATION, PRODUCT, CONTENT, OR MATERIAL INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE WEBSITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.<br /><br />
                    WITHOUT LIMITING THE FOREGOING, UNDER NO CIRCUMSTANCES SHALL WE BE HELD LIABLE FOR ANY DELAY OR FAILURE IN PERFORMANCE RESULTING DIRECTLY OR INDIRECTLY FROM CIRCUMSTANCES BEYOND OUR REASONABLE CONTROL, INCLUDING WITHOUT LIMITATION, INTERNET FAILURES OR DELAYS, COMPUTER EQUIPMENT FAILURES, TELECOMMUNICATION FAILURES, OTHER EQUIPMENT FAILURES, ELECTRICAL POWER FAILURES, STRIKES, LABOR DISPUTES, RIOTS, INSURRECTIONS, CIVIL DISTURBANCES, SHORTAGES OF LABOR OR MATERIALS, FIRES, FLOODS, STORMS, OTHER ACTS OF NATURE, EXPLOSIONS, ACTS OF GOD, WAR, GOVERNMENTAL ACTIONS, ORDERS OF DOMESTIC OR FOREIGN COURTS OR TRIBUNALS, AND NON-PERFORMANCE OF THIRD PARTIES.<br /><br />

                    If there are any problems with the goods shipped to you (such as damage, wrong shipment, etc.), you agree that your rights are limited only to a refund of the price you paid for the damaged goods and that YOU WAIVE ALL OTHER CAUSES OF ACTION OF ANY TYPE OR NATURE OR REMEDIES.<br /><br />

                    The Website does not sell products for purchase by children. We may, however, sell children's products for purchase by adults. The Website is not intended or directed to individuals under the age of 18. We reserve the right to refuse service to any person for any reason or for no reason at all.<br /><br />

                    gorjana does not warrant that the services, information, products, content, materials, or other services included on or otherwise made available to you through the Website, gorjana's servers or electronic communications are free of viruses or other harmful components.
                    <br /><br />
                    If you are dissatisfied with this Website or any of its Content, or with these Terms of Use, your sole and exclusive remedy is to discontinue using this Website.<br /><br />

                    With respect to the AURA READING photo booth (the “Service”) located at one of our retail store locations or online in any way, your use of such Service including the stated results thereof and recommendations made by the agents and staff of gorjana are for entertainment purposes only. The Service is intended for adults 18 years of age and older. The information the gorjana advisors offer to you should not be used in place of any recommendations by medical professionals or other professional counselors. Gorjana wants you to enjoy the Service but it is not scientific and not to be relied upon for any purpose.<br /><br />

                    Any content provided with respect to any properties of any stone or jewelry piece or gorjana product are for entertainment purposes, not scientific and not to be treated as medical advice or relied upon for any purpose.<br /><br />

                    This DISCLAIMER OF WARRANTIES AND LIMITATIONS OF LIABILITY shall apply to the extent not prohibited by applicable law. Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above disclaimers, exclusions, or limitations may not apply to you, and you might have additional rights.<br /><br />

                    To the residents of New Jersey, your rights are protected under the Truth-in-Consumer Contract, Warranty and Notice Act. The provisions in the Limitations of Liability and elsewhere in this Terms of Use and our Privacy Policy may be different than the rights you might enjoy under the laws of New Jersey. Your rights regarding the Limitations of Liability and other provisions in our Terms of Use and Privacy Policy will be governed by applicable New Jersey law and not by the Terms of Use and Privacy Policy to the extent that the provisions are inconsistent with New Jersey law.<br /><br />


                    ARBITRATION CLAUSE AND CLASS ACTION WAIVER.This section is deemed to be a written agreement to arbitrate pursuant to the Federal Arbitration Act (“FAA”), and we and you intend that this section satisfies the writing requirement of the FAA. We believe that arbitration is a faster, more convenient and less expensive way to resolve any disputes or disagreements that you may have with us. Therefore, pursuant to these Terms of Use, if you have any dispute or disagreement with us regarding (i) your use of or interaction with the Website, (ii) any data or information you may enter into the Website or that we may gather in connection with such use or interaction, you will not have the right to pursue a claim in court, or have a jury decide the claim, and you will not have the right to bring or participate in any class action or similar proceeding in court or in arbitration. By using or interacting with the Website, you agree to binding arbitration as provided below.
                    We will make every reasonable effort to informally resolve any complaints, disputes, or disagreements that you may have with us. If those efforts fail, by using our Website, you agree that any complaint, dispute, or disagreement you may have against us, and any claim that we may have against you, arising out of, relating to, or connected in any way with these Terms of Use or our Privacy Policy shall be resolved exclusively by final and binding arbitration (“Arbitration”) administered by JAMS or its successor (“JAMS”) and conducted in accordance with the JAMS Streamlined Arbitration Rules And Procedures in effect at the time the Arbitration is initiated or, if the amount in controversy exceeds $100,000, in accordance with the JAMS Comprehensive Arbitration Rules And Procedures then in effect (respectively, the “Applicable Rules”). The Applicable Rules can be found at www.jamsadr.com. If JAMS is no longer in existence, the Arbitration shall be administered by the American Arbitration Association or its successor (the “AAA”) instead, and conducted in accordance with the AAA Commercial Arbitration Rules in effect at that time (which shall act as the “Applicable Rules” in such circumstances). If the Minimum Standards of Procedural Fairness for Consumer Arbitrations is in effect, in no event may such Minimum Standards contravene or restrict the application of subpart (e) or (i) below. Furthermore, this section shall not prevent any party from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.
                    <br /><br />
                    You further agree that:

                    (a) Single Arbitrator. The Arbitration shall be conducted before a single arbitrator selected in accordance with the Applicable Rules or by mutual agreement between you and us (the “Arbitrator”);<br /><br />
                    (b) Arbitrator Will Interpret This Agreement. The Arbitrator, and not any federal, state or local court or agency, shall have the exclusive authority to resolve any dispute arising under or relating to the validity, interpretation, applicability, enforceability or formation of these Terms of Use and/or these arbitration provisions, including but not limited to any claim that all or any part of these Terms of Use is void or voidable;<br /><br />
                    (c) Location of Arbitration. The Arbitration shall be held either: (i) at a location determined by JAMS (or, if applicable, AAA) pursuant to the Applicable Rules (provided that such location is reasonably convenient for you and does not require travel in excess of 100 miles from your home or place of business); or (ii) at such other location as may be mutually agreed upon by you and us; or (iii) at your election, if the only claims in the arbitration are asserted by you and are for less than $10,000 in aggregate, by telephone or by written submission.<br /><br />
                    (d) Governing Law. The Arbitrator (i) shall apply internal laws of the State of California consistent with the Federal Arbitration Act and applicable statutes of limitations, or, to the extent (if any) that federal law prevails, shall apply the law of the U.S., irrespective of any conflict of law principles; (ii) shall entertain any motion to dismiss, motion to strike, motion for judgment on the pleadings, motion for complete or partial summary judgment, motion for summary adjudication, or any other dispositive motion consistent with California or federal rules of procedure, as applicable; (iii) shall honor claims of privilege recognized at law; and (iv) shall have authority to award any form of legal or equitable relief;<br /><br />
                    (e) No Class Relief. The Arbitration can resolve only your and/or our individual claims, and the Arbitrator shall have no authority to entertain or arbitrate any claims on a class or representative basis, or to consolidate or join the claims of other persons or parties who may be similarly situated. This means that you may not join or consolidate claims in arbitration or litigate in court as a representative or member of a class;
                    (f) Written Award. The Arbitrator shall issue a written award supported by a statement of decision setting forth the Arbitrator’s complete determination of the dispute and the factual findings and legal conclusions relevant to it (an “Award”). Judgment upon the Award may be entered by any court having jurisdiction thereof or having jurisdiction over the relevant party or its assets;<br /><br />
                    (g) Interpretation and Enforcement of Arbitration Clause. With the exception of subpart (e) above, if any part of this arbitration provision is deemed to be invalid, unenforceable or illegal, or otherwise conflicts with the Applicable Rules, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting provision were not contained herein. Furthermore if the arbitration clause is deemed inapplicable or unenforceable then you agree that any legal or equitable claim arising from your use of this Website, or use of our products or services, must be brought in the city, state or federal courts located in Orange County, California.<br /><br />
                    (h) Modification of Arbitration Clause With Notice. We may modify these arbitration provisions, but such modifications shall only become effective thirty (30) days after we have given notice of such modifications and only on a prospective basis for claims arising from your use of or interaction with the Website, or any data or information you may enter into the Website or that we may gather in connection with such use or interaction occurring after the effective date of such notification.<br /><br />
                    (i) Small Claims Matters are Excluded. No Class Relief or Joinder of Claims. Notwithstanding the foregoing arbitration provisions, at your option, you may bring any claim you have against us in your local small claims court within the U.S., if your claim is within such court’s jurisdictional limit; provided that such court does not have the authority to entertain any claims on a class or representative basis, or to consolidate or join the claims of other persons or parties who may be similarly situated in such proceeding.<br /><br />

                    THIS SECTION LIMITS CERTAIN RIGHTS, INCLUDING THE RIGHT TO MAINTAIN A COURT ACTION, THE RIGHT TO A JURY TRIAL, THE RIGHT TO PARTICIPATE IN ANY FORM OF CLASS OR REPRESENTATIVE CLAIM, THE RIGHT TO ENGAGE IN DISCOVERY EXCEPT AS PROVIDED IN ARBITRATION RULES, AND THE RIGHT TO CERTAIN REMEDIES AND FORMS OF RELIEF. OTHER RIGHTS THAT YOU OR gorjana WOULD HAVE IN COURT ALSO MAY NOT BE AVAILABLE IN ARBITRATION. If any provision of this Section is found to be invalid or unenforceable, then that specific provision shall be of no force and effect and shall be severed, but the remainder of this Section will continue in full force and effect. This Section of these Terms will survive the termination of your relationship with gorjana.
                </p>

                <strong>GENERAL PROVISIONS</strong>
                <p>
                    Indemnification: You agree to defend, indemnify and hold harmless gorjana and its affiliates for any violations of these Terms of Use or of the Privacy Policy by you or your agents.<br /><br />

                    Severability: If any of the provisions under these Terms of Use shall be deemed invalid, void, or for any reason unenforceable, that provision shall be deemed severable and shall not affect the validity and enforceability of any remaining provisions.<br /><br />

                    Captions: The captions contained in these Terms of Use and in the Privacy Policy are for convenience of reference only and shall not control or affect the meaning or construction of any of the provisions of these Terms of Use or of the Privacy Policy.<br /><br />

                    Worldwide Applicability: The provisions of this Terms of Use are to apply worldwide.
                </p>

                <strong>EFFECTIVE DATE AND UPDATES<strong>GENERAL PROVISIONS</strong></strong>
                <p>The effective date of these Terms of Use is March 4, 2021. We may update the Terms of Use at any time in our sole discretion. When it is updated, the updated Terms of Use will be made available on the Website for your convenience.</p>

            </div>
            <div style={{ marginTop: '50px' }}>
                <Footer />
            </div>
        </div>
    )
}
